version: "3"
services:
  server:
    image: "node:lts-alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./server/:/home/node/app
    command: ash -c "npm i && node index.js"
    restart: unless-stopped
    networks:
      - https_net
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.snapdrop-server.rule=Host(`snapdrop.kbauer.at`, `sd.kbauer.at`) && PathPrefix(`/server`)"
      - "traefik.http.services.snapdrop-server.loadbalancer.server.port=3000"
      - "traefik.http.routers.snapdrop-server.tls=true"
      - "traefik.http.routers.snapdrop-server.tls.certresolver=myresolver"
  client:
    image: nginx:alpine
    volumes:
      - ./client:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - https_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.snapdrop-client.rule=Host(`snapdrop.kbauer.at`, `sd.kbauer.at`) && !PathPrefix(`/server`)"
      - "traefik.http.services.snapdrop-client.loadbalancer.server.port=80"
      - "traefik.http.routers.snapdrop-client.tls=true"
      - "traefik.http.routers.snapdrop-client.tls.certresolver=myresolver"

networks:
  https_net:
    external: true
  default:
